version: '3'
services:
  app:
    image: joy-toys
    command: npm run test-coverage
    build:
      context: .
      dockerfile: Dockerfile
    environment:
     #- MONGODB_CONNECTION_STRING=${MONGODB_CONNECTION_STRING} for remote database
     - MONGODB_CONNECTION_STRING=mongodb://mongo/joy-toys-local
    ports:
      - 3000:3000
      - 35729:35729
    volumes:
      - ./src:/app/src
      - ./test:/app/test
  mongo:
    image: mongo
    ports:
      - 27017:27017
