version: '3'
services:
  app:
    image: sose-sw207
    build:
      context: .
      dockerfile: Dockerfile
    environment:
     #- MONGODB_CONNECTION_STRING=${MONGODB_CONNECTION_STRING}
     #- MONGODB_CONNECTION_STRING=mongodb://mongo/express-mongo-docker-project 
      - MONGODB_CONNECTION_STRING=mongodb://mongo/mongodb  # buraya ne yazmaliyim?
    ports:
      - 3000:3000
      - 35729:35729
    volumes:
      - ./src:/app/src
      - ./test:/app/test
  mongo:
    image: mongo
    ports:
      - 27019:27017
